-- 정렬 기능 알아보기
-- ORDER BY

-- 내림차순 정렬
SELECT 
	*
  FROM TBL_MENU
 ORDER BY MENU_CODE DESC;


-- 오름차순 정렬 
SELECT 
	*
  FROM TBL_MENU
 ORDER BY MENU_CODE ASC;

-- 오름차순 정렬 기본 값은 ASC
SELECT 
	*
  FROM TBL_MENU
 ORDER BY MENU_CODE ;

-- ORDER BY 절을 사용하여 결과 집합을 여러 열로 정렬
SELECT 
	MENU_CODE ,
	MENU_NAME ,
	MENU_PRICE 
  FROM TBL_MENU
 ORDER BY 
 	MENU_PRICE DESC ,
 	MENU_CODE ASC;
 
-- 열산 결과로 결과 집합 정렬
-- 아래의 결과는 두번 연산이 진행되는 것으로 판단됨
-- 데이터의 값이 증가할 수 록 성능이 저하된다.
SELECT 
	MENU_CODE,
	MENU_PRICE,
	(MENU_CODE * MENU_PRICE)
  FROM TBL_MENU
 ORDER BY 
 	MENU_CODE * MENU_PRICE;
-- 위의 연산의 경우 다음과 같이 사용하는 것이 좋다..
 SELECT 
	MENU_CODE,
	MENU_PRICE,
	(MENU_CODE * MENU_PRICE) AS '메뉴코드와 가격을 곱함'
  FROM TBL_MENU
 ORDER BY 
 	'메뉴코드와 가격을 곱함';
 
SELECT FIELD('A','A','B','C');
SELECT FIELD('B','A','B','C'); 

SELECT
	menu_code,
	menu_name,
	ORDERABLE_STATUS,
	FIELD(ORDERABLE_STATUS, 'N', 'Y')
  FROM TBL_MENU;
  
 SELECT * FROM tbl_menu;
 
SELECT 
	menu_name,
	orderable_status,
	FIELD(ORDERABLE_STATUS, 'N', 'Y')
  FROM TBL_MENU
 ORDER BY FIELD(ORDERABLE_STATUS, 'N','Y') DESC; 
 
-- null
-- 오름차순 시 null 처음으로(default)
SELECT 
	CATEGORY_CODE ,
	CATEGORY_NAME ,
	REF_CATEGORY_CODE 
  FROM TBL_CATEGORY
 ORDER BY 
 	REF_CATEGORY_CODE;
 
-- 역순으로 정렬시
-- DESC
 SELECT 
	CATEGORY_CODE ,
	CATEGORY_NAME ,
	REF_CATEGORY_CODE 
  FROM TBL_CATEGORY
 ORDER BY 
 	REF_CATEGORY_CODE DESC;
 
-- 오름 차순시 마지막으로 정렬
SELECT 
	CATEGORY_CODE ,
	CATEGORY_NAME ,
	REF_CATEGORY_CODE 
  FROM TBL_CATEGORY
 ORDER BY 
 	REF_CATEGORY_CODE IS NULL; 
 
 -- 내림 차순시 처음으로 정렬
SELECT 
	CATEGORY_CODE ,
	CATEGORY_NAME ,
	REF_CATEGORY_CODE 
  FROM TBL_CATEGORY
 ORDER BY 
 	REF_CATEGORY_CODE IS NULL DESC; 

 
